apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: var_nombrePipeline
spec:
  params:
    - default: var_nombreApp
      name: APP_NAME
      type: string
    - default: var_urlRepoGit
      name: GIT_REPO
      type: string
    - default: dev
      name: GIT_REVISION
      type: string
    - default: var_rutaImagen
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: openjdk-11:1.18-2
      name: VERSION
      type: string
  tasks:
    - name: obtener-codigo
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: compilar
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - compile
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - obtener-codigo
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: workspace
    - name: construir-imagen
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - compilar
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
    - name: despliegue
      params:
        - name: ARGS
          value:
            - rollout
            - latest
            - dc/$(params.APP_NAME)
      runAfter:
        - construir-imagen
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
